dist: easy_check
language: python
python:
  - "3.7.0"  # 3.7 development branch
# command to install dependencies
install:
  - sudo apt-get install ruby-coveralls
  - python setup.py install
script:
  - pytest

after_success:
  - coveralls